'use client';

import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {loadWorkflow,type WorkflowState} from '@/lib/workflow-store';
import type {DemoUser} from '@/lib/demo-users';
import './report.css';

export default function ExecutiveReportPage(){
  const router=useRouter();
  const [user,setUser]=useState<DemoUser|null>(null);
  const [flow,setFlow]=useState<WorkflowState|null>(null);
  useEffect(()=>{
    const raw=localStorage.getItem('hrox-session');
    if(!raw){router.replace('/');return}
    setUser(JSON.parse(raw));
    setFlow(loadWorkflow());
  },[router]);
  if(!user||!flow)return null;
  const completed=flow.assignments.filter(a=>a.status==='Completed').length;
  const submitted=flow.assignments.filter(a=>a.status==='Report submitted').length;
  const overdue=flow.assignments.filter(a=>a.status==='Overdue').length;
  const coverage=new Set(flow.assignments.map(a=>a.project)).size;
  return <main className="reportPage">
    <header className="reportHeader"><div><div className="eyebrow">HROX executive report</div><h1>{flow.requestTitle}</h1><p>{flow.requestPeriod}</p></div><div className="noPrint"><button className="demo" onClick={()=>router.push('/dashboard')}>Back</button><button className="primary" onClick={()=>window.print()}>Print / Save PDF</button></div></header>
    <section className="reportMeta"><div><small>Prepared for</small><b>{user.name}</b></div><div><small>Workflow stage</small><b>{flow.stage}</b></div><div><small>Generated</small><b>{new Date().toLocaleString()}</b></div></section>
    <section className="cards reportKpis"><div className="card"><small>Completion rate</small><strong>{flow.assignments.length?Math.round(completed/flow.assignments.length*100):0}%</strong></div><div className="card"><small>Project coverage</small><strong>{coverage}</strong></div><div className="card"><small>Pending review</small><strong>{submitted}</strong></div><div className="card"><small>Risk alerts</small><strong>{overdue}</strong></div></section>
    <section className="card section"><h2>Assignment summary</h2><div className="tableWrap"><table><thead><tr><th>ID</th><th>Project</th><th>Manager</th><th>Period</th><th>Status</th><th>Report summary</th></tr></thead><tbody>{flow.assignments.map(a=><tr key={a.id}><td>{a.id}</td><td>{a.project}</td><td>{a.managerName}</td><td>{a.startDate} → {a.endDate}</td><td>{a.status}</td><td>{a.reportSummary||'—'}</td></tr>)}</tbody></table></div></section>
    <section className="card section"><h2>Management observations</h2><ul>{flow.assignments.filter(a=>a.notes.length||a.coordinatorComment).map(a=><li key={a.id}><b>{a.project}:</b> {[...a.notes,a.coordinatorComment].filter(Boolean).join(' · ')}</li>)}</ul></section>
    <footer className="reportFooter">Generated by HROX · Project HR Rotation & Field Operations</footer>
  </main>
}
