'use client';

import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {DemoUser} from '@/lib/demo-users';
import {loadWorkflow,resetWorkflow,saveWorkflow,type Assignment,type WorkflowState} from '@/lib/workflow-store';

const projects=['Mataf Expansion','Shamiyah Development','Makkah Gate','Central Utility','Haram Security','North Plaza'];
const managers=[{name:'Omar Khaled',email:'manager1@hrox.demo'},{name:'Sara Nabil',email:'manager2@hrox.demo'}];
const stages=['request','planning','review','assigned','fieldwork','reporting','executive'];

export default function DashboardPage(){
 const router=useRouter();
 const [user,setUser]=useState<DemoUser|null>(null);
 const [flow,setFlow]=useState<WorkflowState|null>(null);
 const [tab,setTab]=useState('overview');
 useEffect(()=>{const raw=localStorage.getItem('hrox-session');if(!raw){router.replace('/');return}setUser(JSON.parse(raw));setFlow(loadWorkflow())},[router]);
 const persist=(next:WorkflowState)=>{setFlow(next);saveWorkflow(next)};
 const log=(next:WorkflowState,message:string)=>persist({...next,activity:[new Date().toLocaleString()+' — '+message,...next.activity]});
 const myAssignments=useMemo(()=>!user||!flow?[]:user.role==='manager'?flow.assignments.filter(a=>a.managerEmail===user.email):flow.assignments,[user,flow]);
 if(!user||!flow)return null;
 const canEditPlan=user.role==='coordinator'||(user.role==='director'&&flow.stage==='review');
 const updateAssignment=(id:string,patch:Partial<Assignment>)=>persist({...flow,assignments:flow.assignments.map(a=>a.id===id?{...a,...patch}:a)});
 const addAssignment=()=>{const n=flow.assignments.length+1;persist({...flow,assignments:[...flow.assignments,{id:`A-${String(n).padStart(3,'0')}`,project:projects[0],managerEmail:managers[0].email,managerName:managers[0].name,startDate:'2026-08-10',endDate:'2026-08-12',status:'Scheduled',notes:[],attachments:[],reportSummary:'',coordinatorComment:'',selectedForConsolidation:false}]})};
 const gpsCheckIn=(a:Assignment)=>{if(!navigator.geolocation){alert('Location is not supported on this device');return}navigator.geolocation.getCurrentPosition(p=>{updateAssignment(a.id,{status:'Checked in',checkIn:{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:new Date().toISOString()}});},()=>alert('Location permission is required for GPS check-in'),{enableHighAccuracy:true,timeout:10000})};
 const attach=(a:Assignment,file:File|null)=>{if(!file)return;const url=URL.createObjectURL(file);updateAssignment(a.id,{attachments:[...a.attachments,{name:file.name,url,uploadedAt:new Date().toISOString()}]})};
 const submitReport=(a:Assignment)=>{if(!a.reportSummary.trim()){alert('Please add the final report summary first');return}const assignments=flow.assignments.map(x=>x.id===a.id?{...x,status:'Report submitted' as const}:x);log({...flow,stage:'reporting',assignments},`${user.name} submitted field report for ${a.project}`)};
 const selected=flow.assignments.filter(a=>a.selectedForConsolidation&&a.status==='Completed');
 const exportCsv=()=>{const rows=[['ID','Project','Manager','Start','End','Status','Notes','Report'],...flow.assignments.map(a=>[a.id,a.project,a.managerName,a.startDate,a.endDate,a.status,String(a.notes.length),a.reportSummary])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='hrox-rotation-report.csv';link.click();URL.revokeObjectURL(url)};
 const completed=flow.assignments.filter(a=>a.status==='Completed').length;
 const overdue=flow.assignments.filter(a=>a.status==='Overdue').length;
 const submitted=flow.assignments.filter(a=>a.status==='Report submitted').length;
 const coverage=new Set(flow.assignments.map(a=>a.project)).size;
 const nav=['overview','request','plan','assignments','reports','audit'];
 const stageText={request:'Waiting for Director request',planning:'Coordinator preparing plan',review:'Director reviewing plan',assigned:'Assignments released',fieldwork:'Field visits in progress',reporting:'Reports under coordinator review',executive:'Executive dashboard ready'}[flow.stage];
 return <main className="shell"><aside className="side"><div className="sideBrand"><div className="mark">H</div><span>HROX</span></div><nav className="nav">{nav.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav></aside><section className="main"><header className="top"><div><div className="eyebrow">{user.title}</div><h1>{user.name}</h1><p className="sub">{stageText}</p></div><div className="topActions"><span className="statusChip">{flow.stage}</span><button className="demo" onClick={()=>{localStorage.removeItem('hrox-session');router.replace('/')}}>Sign out</button></div></header>
 {tab==='overview'&&<><div className="cards"><div className="card"><small>Workflow stage</small><strong>{flow.stage}</strong></div><div className="card"><small>Assignments</small><strong>{myAssignments.length}</strong></div><div className="card"><small>Reports submitted</small><strong>{submitted+completed}</strong></div><div className="card"><small>Overdue</small><strong>{overdue}</strong></div></div><section className="card section"><div className="sectionHead"><div><div className="eyebrow">End-to-end process</div><h2>Rotation cycle status</h2></div><button className="demo" onClick={()=>{resetWorkflow();location.reload()}}>Reset demo</button></div><div className="steps">{stages.map((s,i)=>{const current=stages.indexOf(flow.stage);return <div key={s} className={`flowStep ${i<current?'done':i===current?'current':''}`}><b>{i<current?'✓':i===current?'●':'○'} {s}</b><small>{i<current?'Completed':i===current?'In progress':'Upcoming'}</small></div>})}</div></section>{user.role==='director'&&<section className="card section"><div className="sectionHead"><div><div className="eyebrow">Decision intelligence</div><h2>Executive dashboard</h2></div><button className="demo" onClick={exportCsv}>Export CSV</button></div><div className="cards analytics"><div className="card"><small>Completion rate</small><strong>{flow.assignments.length?Math.round(completed/flow.assignments.length*100):0}%</strong></div><div className="card"><small>Project coverage</small><strong>{coverage}</strong></div><div className="card"><small>Pending review</small><strong>{submitted}</strong></div><div className="card"><small>Risk alerts</small><strong>{overdue}</strong></div></div><p className="sub">Use completion, overdue, project coverage and field-report patterns to support management decisions.</p></section>}</>}
 {tab==='request'&&<section className="card section"><div className="eyebrow">Step 1</div><h2>Rotation plan request</h2><div className="formGrid"><label>Request title<input value={flow.requestTitle} onChange={e=>persist({...flow,requestTitle:e.target.value})} disabled={user.role!=='director'||flow.stage!=='request'}/></label><label>Period<input value={flow.requestPeriod} onChange={e=>persist({...flow,requestPeriod:e.target.value})} disabled={user.role!=='director'||flow.stage!=='request'}/></label><label className="wide">Instructions<textarea value={flow.requestInstructions} onChange={e=>persist({...flow,requestInstructions:e.target.value})} disabled={user.role!=='director'||flow.stage!=='request'}/></label></div>{user.role==='director'&&flow.stage==='request'&&<button className="primary actionBtn" onClick={()=>log({...flow,stage:'planning'},'Director sent planning request to Coordinator')}>Send to Coordinator</button>}</section>}
 {tab==='plan'&&<section className="card section"><div className="sectionHead"><div><div className="eyebrow">Shared planning workspace</div><h2>{flow.requestTitle}</h2><p className="sub">Coordinator builds the plan. Director can edit people, projects and dates before approval.</p></div>{canEditPlan&&<button className="demo" onClick={addAssignment}>+ Add assignment</button>}</div><div className="tableWrap"><table><thead><tr><th>ID</th><th>Project</th><th>Assigned manager</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody>{flow.assignments.map(a=><tr key={a.id}><td>{a.id}</td><td>{canEditPlan?<select value={a.project} onChange={e=>updateAssignment(a.id,{project:e.target.value})}>{projects.map(p=><option key={p}>{p}</option>)}</select>:a.project}</td><td>{canEditPlan?<select value={a.managerEmail} onChange={e=>{const m=managers.find(x=>x.email===e.target.value)!;updateAssignment(a.id,{managerEmail:m.email,managerName:m.name})}}>{managers.map(m=><option value={m.email} key={m.email}>{m.name}</option>)}</select>:a.managerName}</td><td>{canEditPlan?<input type="date" value={a.startDate} onChange={e=>updateAssignment(a.id,{startDate:e.target.value})}/>:a.startDate}</td><td>{canEditPlan?<input type="date" value={a.endDate} onChange={e=>updateAssignment(a.id,{endDate:e.target.value})}/>:a.endDate}</td><td><span className="statusChip">{a.status}</span></td></tr>)}</tbody></table></div><div className="workflowActions">{user.role==='coordinator'&&flow.stage==='planning'&&<button className="primary actionBtn" onClick={()=>log({...flow,stage:'review'},'Coordinator submitted plan to Director')}>Submit to Director</button>}{user.role==='director'&&flow.stage==='review'&&<><input className="comment" placeholder="Director comment" value={flow.directorComment} onChange={e=>persist({...flow,directorComment:e.target.value})}/><button className="demo" onClick={()=>log({...flow,stage:'planning'},'Director returned plan to Coordinator')}>Return for changes</button><button className="primary actionBtn" onClick={()=>log({...flow,stage:'assigned'},'Director approved plan; assignments released automatically')}>Approve & release</button></>}</div></section>}
 {tab==='assignments'&&<section className="card section"><div className="eyebrow">Role-based assignment workspace</div><h2>{user.role==='manager'?'My field assignments':'All assignments'}</h2><div className="assignmentGrid">{myAssignments.map(a=><article className="assignment" key={a.id}><div className="sectionHead"><div><b>{a.project}</b><p className="sub">{a.startDate} → {a.endDate}</p></div><span className="statusChip">{a.status}</span></div><p><b>Assigned to:</b> {a.managerName}</p>{a.checkIn&&<p className="sub">GPS: {a.checkIn.latitude.toFixed(5)}, {a.checkIn.longitude.toFixed(5)} · accuracy {Math.round(a.checkIn.accuracy)}m</p>}{user.role==='manager'&&flow.stage!=='request'&&flow.stage!=='planning'&&flow.stage!=='review'&&<><div className="workflowActions"><button className="demo" onClick={()=>gpsCheckIn(a)}>GPS Check-in</button><button className="demo" onClick={()=>{const text=prompt('Daily note');if(text)updateAssignment(a.id,{status:'In progress',notes:[...a.notes,text]})}}>Add daily note</button><label className="demo upload">Attach evidence<input type="file" hidden onChange={e=>attach(a,e.target.files?.[0]||null)}/></label></div><textarea className="reportBox" placeholder="Final report summary" value={a.reportSummary} onChange={e=>updateAssignment(a.id,{reportSummary:e.target.value})}/><button className="primary actionBtn" onClick={()=>submitReport(a)}>Submit report</button></>}<ul>{a.notes.map((n,i)=><li key={i}>{n}</li>)}</ul>{a.attachments.length>0&&<div className="attachments">{a.attachments.map((f,i)=><a href={f.url} target="_blank" key={i}>{f.name}</a>)}</div>}{a.coordinatorComment&&<p className="returnComment"><b>Coordinator:</b> {a.coordinatorComment}</p>}</article>)}</div></section>}
 {tab==='reports'&&<section className="card section"><div className="sectionHead"><div><div className="eyebrow">Coordinator & executive reporting</div><h2>Submitted reports</h2></div>{user.role==='coordinator'&&<span className="statusChip">{selected.length} selected</span>}</div><div className="tableWrap"><table><thead><tr>{user.role==='coordinator'&&<th>Select</th>}<th>Project</th><th>Manager</th><th>Status</th><th>Notes</th><th>Action</th></tr></thead><tbody>{flow.assignments.map(a=><tr key={a.id}>{user.role==='coordinator'&&<td><input type="checkbox" checked={a.selectedForConsolidation} disabled={a.status!=='Completed'} onChange={e=>updateAssignment(a.id,{selectedForConsolidation:e.target.checked})}/></td>}<td>{a.project}</td><td>{a.managerName}</td><td>{a.status}</td><td>{a.notes.length}</td><td>{user.role==='coordinator'&&a.status==='Report submitted'?<div className="rowActions"><button className="demo" onClick={()=>{const comment=prompt('Return comment');if(comment)updateAssignment(a.id,{status:'Returned',coordinatorComment:comment})}}>Return</button><button className="demo" onClick={()=>updateAssignment(a.id,{status:'Completed',coordinatorComment:''})}>Accept</button></div>:'—'}</td></tr>)}</tbody></table></div>{user.role==='coordinator'&&selected.length>0&&<button className="primary actionBtn" onClick={()=>log({...flow,stage:'executive'},`Coordinator submitted ${selected.length} selected report(s) to Director`)}>Submit selected reports to Director</button>}{user.role==='director'&&flow.stage==='executive'&&<div className="executive"><h3>Decision dashboard</h3><p className="sub">The consolidated report is ready. Review selected completed assignments, risks and observations before taking action.</p><button className="demo" onClick={exportCsv}>Download consolidated CSV</button></div>}</section>}
 {tab==='audit'&&<section className="card section"><div className="eyebrow">Governance</div><h2>Audit history</h2><ul className="auditList">{flow.activity.map((x,i)=><li key={i}>{x}</li>)}</ul></section>}
 </section></main>
}